# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Messy Rest Home 

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: In the House of Butter 

description: Stylish Jekyll Theme
author:
  name: Todd
  email: toddevanbowser@gmail.com
  github: minorfires
  twitter: minorfires
  bio: for tall humans and normal-sized dogs.
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: http://img2-ak.lst.fm/i/u/300x300/a45cb3eb6d3d1714504f9c8fdffe2e73.jpg

BASE_PATH:


gems:
  - jekyll-paginate